name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Install dependencies
        run: yarn install

      - name: Build production app
        run: yarn build